<<<<<<< HEAD
# Generated by Django 2.0.12 on 2019-05-09 10:42
=======
# Generated by Django 2.0.12 on 2019-05-09 10:29
>>>>>>> 179e61dbddb0904127c8715edb6e9a1cf02e0095

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('df_user', '0001_initial'),
        ('df_goods', '0001_initial'),
<<<<<<< HEAD
=======
        ('df_user', '0001_initial'),
>>>>>>> 179e61dbddb0904127c8715edb6e9a1cf02e0095
    ]

    operations = [
        migrations.CreateModel(
            name='CartInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_goods.GoodsInfo', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_user.UserInfo', verbose_name='用户')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
            },
        ),
    ]
