# Generated by Django 2.0.12 on 2019-05-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsinfo',
            name='gkeep',
            field=models.IntegerField(default=0, verbose_name='保留数量'),
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='gmin',
            field=models.IntegerField(default=0, verbose_name='最小库存'),
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='gstock',
            field=models.IntegerField(default=0, verbose_name='再进货数量'),
        ),
    ]
