# Generated by Django 2.0.12 on 2019-05-08 23:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0005_auto_20190508_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeinfo',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='typeinfo',
            name='category_type',
            field=models.IntegerField(choices=[(1, '一级类目'), (2, '二级类目'), (3, '三级类目')], default=(1, '一级类目'), help_text='类目级别', verbose_name='类目级别'),
        ),
        migrations.AddField(
            model_name='typeinfo',
            name='code',
            field=models.CharField(default='', help_text='类别code', max_length=30, verbose_name='类别code'),
        ),
        migrations.AddField(
            model_name='typeinfo',
            name='desc',
            field=models.TextField(default='', help_text='类别描述', verbose_name='类别描述'),
        ),
        migrations.AddField(
            model_name='typeinfo',
            name='parent_category',
            field=models.ForeignKey(blank=True, help_text='父目录', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='df_goods.TypeInfo', verbose_name='父类目级别'),
        ),
        migrations.AlterField(
            model_name='typeinfo',
            name='ttitle',
            field=models.CharField(max_length=20, verbose_name='类别名'),
        ),
    ]
